/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Firebase ID token for internal JWT */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user (requires role set) */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set role once during onboarding */
        post: operations["set_role_auth_role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand/campaign-builder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Brand-only gate confirming the caller can reach the campaign builder
         * @description Server-enforced brand gate (A5 AC2). `_require_brand` 403s influencers;
         *     `profile_complete` tells the client whether brand setup is done so it can route
         *     straight into the builder (C1) or back to profile setup.
         */
        get: operations["campaign_builder_access_brand_campaign_builder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get brand profile */
        get: operations["get_profile_brand_profile_get"];
        /** Create or update brand profile */
        put: operations["put_profile_brand_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/influencer/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get influencer profile */
        get: operations["get_profile_influencer_profile_get"];
        /** Create or update influencer profile */
        put: operations["put_profile_influencer_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/influencer/profile/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Instagram or YouTube; fetches and stores verified metrics */
        post: operations["connect_social_influencer_profile_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrandProfileResponse */
        BrandProfileResponse: {
            /** Company Name */
            company_name: string;
            /** Gst */
            gst: string | null;
            /** Industry */
            industry: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Website */
            website: string;
        };
        /** BrandProfileUpdateRequest */
        BrandProfileUpdateRequest: {
            /** Company Name */
            company_name: string;
            /** Gst */
            gst?: string | null;
            /** Industry */
            industry: string;
            /** Website */
            website: string;
        };
        /** CampaignBuilderAccessResponse */
        CampaignBuilderAccessResponse: {
            /** Can Create Campaign */
            can_create_campaign: boolean;
            /** Profile Complete */
            profile_complete: boolean;
        };
        /** ConnectSocialRequest */
        ConnectSocialRequest: {
            /** Oauth Code */
            oauth_code: string;
            platform: components["schemas"]["Platform"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Service health probe response.
         */
        Health: {
            /** Db */
            db: boolean;
            /** Redis */
            redis: boolean;
            /**
             * Status
             * @example ok
             */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Firebase Token */
            firebase_token: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            role: components["schemas"]["Role"] | null;
            /** Role Set */
            role_set: boolean;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string | null;
            /** Firebase Uid */
            firebase_uid: string;
            role: components["schemas"]["Role"];
            /** Role Set */
            role_set: boolean;
        };
        /**
         * Platform
         * @enum {string}
         */
        Platform: "instagram" | "youtube";
        /** ProfileResponse */
        ProfileResponse: {
            /** Bio */
            bio: string | null;
            /** Categories */
            categories: string[];
            /** Niche */
            niche: string | null;
            /**
             * Social Accounts
             * @default []
             */
            social_accounts: components["schemas"]["SocialAccountOut"][];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Verified */
            verified: boolean;
        };
        /** ProfileUpdateRequest */
        ProfileUpdateRequest: {
            /** Bio */
            bio?: string | null;
            /** Categories */
            categories?: string[];
            /** Niche */
            niche?: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "influencer" | "brand" | "admin";
        /** SetRoleRequest */
        SetRoleRequest: {
            role: components["schemas"]["Role"];
        };
        /** SetRoleResponse */
        SetRoleResponse: {
            role: components["schemas"]["Role"];
            /** Role Set */
            role_set: boolean;
        };
        /** SocialAccountOut */
        SocialAccountOut: {
            /**
             * Connected At
             * Format: date-time
             */
            connected_at: string;
            /** Engagement Rate */
            engagement_rate: number;
            /** Followers */
            followers: number;
            platform: components["schemas"]["Platform"];
            /** Reach */
            reach: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    set_role_auth_role_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_builder_access_brand_campaign_builder_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignBuilderAccessResponse"];
                };
            };
        };
    };
    get_profile_brand_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileResponse"];
                };
            };
        };
    };
    put_profile_brand_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_profile_influencer_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    put_profile_influencer_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_social_influencer_profile_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectSocialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
